Taifa_sacco/urls.py
"""
URL configuration for djangoProject1 project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/4.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path


from django.contrib import admin
from django.urls import path

from django.urls import path
from . import views
from django.urls import include, path
from .views import loan_prediction, view_saved_predictions,prediction_report
from .views import custom_logout


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home ,name='home'),
    path('loan_prediction/', loan_prediction, name='loan_prediction'),
    path('predict/', views.predict, name='predict'),
    path('predict/loan_prediction/', views.loan_prediction, name='loan_prediction'),
    path('authentication/', include('authentication.urls'), name='authentication'),
    path('saved/', view_saved_predictions, name='view_saved_predictions'),
    path('report/', prediction_report, name='prediction_report'),
    path('logout/', custom_logout, name='logout'),
 
    
   

   
 # Add a name for the result view
]

admin.site.site_header = "Taifa Sacco Admin"
admin.site.site_title = "Taifa Sacco Admin Portal"
admin.site.index_title = "Welcome to Taifa Sacco  Portal"
# your_project/urls.py


from django.urls import path

authentication/urls.py
app_name = 'authentication'
from django.urls import path
from .views import register, login, update_account, delete_account,services,members


app_name = 'authentication'
from django.urls import path
from .views import register, user_login, update_account, delete_account

urlpatterns = [
    path('register/', register, name='register'),
    path('user_login/', user_login, name='login'),
    path('update_account/', update_account, name='update_account'),
    path('delete_account/', delete_account, name='delete_account'),
    
    path('services/',services,name='ourservice'),
    path('members/',members,name='ourmembers'),
]

templates/home.html
{% load  static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic introduction -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Taifa Sacco Credit Risk Prediction System</title>

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-GLhlTQ8iN17Sme8kATtZ8z9HgB2IbrJDOONT7vo1OqU/E15I6ZuPmXzme17FBo" crossorigin="anonymous">

  <!-- bootstrap core css -->
  
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
  <!-- fonts awesome style -->
  
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,500,700&display=swap" rel="stylesheet" />

  <!-- Custom styles for this template -->
  
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <!-- responsive style -->
  
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
</head>
  <!--Start of Tawk.to Script-->
  <script type="text/javascript">
    var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
    (function(){
    var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
    s1.async=true;
    s1.src='https://embed.tawk.to/64479d7131ebfa0fe7fa4aac/1gurru1lr';
    s1.charset='UTF-8';
    s1.setAttribute('crossorigin','*');
    s0.parentNode.insertBefore(s1,s0);
    })();
    </script>
    <!--End of Tawk.to Script-->
<body>
  <style>
    /* static/css/style.css */

.hero_area {
    background-image: url('{% static "taifa4.PNG" %}');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    height: 100vh; /* Adjust the height as needed */
}

/* Add any additional styles for other elements on the page */

  </style>
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="contact_nav_container">
        <div class="container">
          <div class="contact_nav">
            <a href="">
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              <span>
                Taifa Sacco
              </span>
            </a>
            <a href="">
              <i class="fa fa-envelope" aria-hidden="true"></i>
              <span>
                Email : taifasacco@gmail.com
              </span>
            </a>
            <a href="">
              <i class="fa fa-phone" aria-hidden="true"></i>
              <span>
                Phone Call :0792761073
              </span>
            </a>
          </div>
        </div>
      </div>
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container">
          <div class="custom_menu-btn">
            <button onclick="openNav()">
              <span class="s-1"> </span>
              <span class="s-2"> </span>
              <span class="s-3"> </span>
            </button>
          </div>
          <div id="myNav" class="overlay">
            <div class="menu_btn-style ">
              <button onclick="closeNav()">
                <span class="s-1"> </span>
                <span class="s-2"> </span>
                <span class="s-3"> </span>
              </button>
            </div>
            <div class="overlay-content">
              <a class="active" href="index.html"> Home <span class="sr-only">(current)</span></a>
              <a class="" href="about.html"> About</a>
              <a class="" href="why.html"> Why Us </a>
              <a class="" href="team.html"> Our Team</a>
              <a class="" href="testimonial.html"> Testimonial</a>
              <a class="" href="contact.html"> Contact Us</a>
            </div>
          </div>
          <a class="navbar-brand" href="index.html">
            <span>
              
            </span>
          </a>

          <span>
            
            <a href="{% url 'authentication:ourservice'%}">Services</a>
          </span>

          <span>
           
            <a href="{% url 'authentication:ourmembers'%}"> Membership</a>
          </span>

          <span>
           
            <a href="{% url 'authentication:login' %}"> Our Products</a>
          </span>

          <div class="user_option">
           
            <a href="{% url 'authentication:login' %}">
              <span>
                Login
              </span>
              <i class="fa fa-user" aria-hidden="true"></i>
            </a>
           
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->
    <!-- slider section -->
    <section class="slider_section position-relative">
      <div id="customCarousel1" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#customCarousel1" data-slide-to="0" class="active"></li>
          <li data-target="#customCarousel1" data-slide-to="1"></li>
          <li data-target="#customCarousel1" data-slide-to="2"></li>
          <li data-target="#customCarousel1" data-slide-to="3"></li>
        </ol>
        
        
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="box">
              <div class="baby_detail">
                <div class="baby_text">
                  <h4>
                    Loan <br />
                    with Us
                  </h4>
                </div>
                <a href="">
                  Read More
                </a>
              </div>
              <div class="care_detail">
              <a href="">
                  Contact Us
                </a>
                <div class="care_text">
                  <h4>
                    Check your <br /> 
                    Loan <br />
                    Eligibility
                  </h4>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="box">
              <div class="baby_detail">
                <div class="baby_text">
                  <h4>
                    Loan  <br />
                    with us
                  </h4>
                </div>
                <a href="">
                  Read More
                </a>
              </div>
              <div class="care_detail">
               <a href="">
                  Contact Us
                </a>
                <div class="care_text">
                  <h4>
                    Check your <br /> 
                    Loan <br />
                    Eligibility
                  </h4>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="box">
              <div class="baby_detail">
                <div class="baby_text">
                  <h4>
                    Loan  <br />
                    with us
                  </h4>
                </div>
                <a href="">
                  Read More
                </a>
              </div>
              <div class="care_detail">
                <a href="">
                  Contact Us
                </a>
                <div class="care_text">
                  <h4>
                    Check your <br /> 
                    Loan <br />
                    Eligibility
                  </h4>
                </div>
              </div>
            </div>
          </div>
          <div class="carousel-item">
            <div class="box">
              <div class="baby_detail">
                <div class="baby_text">
                  <h4>
                    Loan  <br />
                    with us
                  </h4>
                </div>
                <a href="">
                  Read More
                </a>
              </div>
              <div class="care_detail">
                <a href="">
                  Contact Us
                </a>
                <div class="care_text">
                  <h4>
                    Check your <br /> 
                    Loan <br />
                    Eligibility
                  </h4>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <!-- end slider section -->
  </div>

  <!-- service section -->

 

  

  <section class="info_section layout_padding2">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="info_contact">
            <h5>
              Address
            </h5>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call 0792761073
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  taifasacco@gmail.com
                </span>
              </a>
            </div>
          </div>
          <div class="info_social">
            <a href="">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-linkedin" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-instagram" aria-hidden="true"></i>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="info_link_box">
            <h5>
              Navigation
            </h5>
            <div class="info_links">
              <a class="active" href="index.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Home <span class="sr-only">(current)</span></a>
              <a class="" href="about.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> About</a>
              <a class="" href="why.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Why Us </a>
              <a class="" href="team.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Our Team</a>
              <a class="" href="testimonial.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Testimonial</a>
              <a class="" href="contact.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Contact Us</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <h5>
            Newsletter
          </h5>
          <form action="">
            <input type="text" placeholder="Enter Your email" />
            <button type="submit">
              Subscribe
            </button>
          </form>
        </div>
      </div>
    </div>
  </section>

  <!-- end info section -->

  <!-- footer section -->
  <footer class="footer_section container-fluid">
    <p>
      &copy; <span id="displayYear"></span> All Rights Reserved. Developed By
      <a href="https://developer-fullstack.netlify.app/">Bruno</a>
    </p>
  </footer>
  <!-- footer section -->

  
  <script src="{% static 'js/jquery-3.4.1.min.js' %} "></script>
  <script src="{% static 'js/bootstrap.js' %} "></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
  <script src="{% static 'js/custom.js' %} "></script>
  
  


</body>

</html>

templates/login.html
{% load  static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Taifa Sacco Credit Risk Prediction System</title>

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-GLhlTQ8iN17Sme8kATtZ8z9HgB2IbrJDOONT7vo1OqU/E15I6ZuPmXzme17FBo" crossorigin="anonymous">

  <!-- bootstrap core css -->
  
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
  <!-- fonts awesome style -->
  
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,500,700&display=swap" rel="stylesheet" />

  <!-- Custom styles for this template -->
  
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <!-- responsive style -->
  
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
</head>
  <!--Start of Tawk.to Script-->
  <script type="text/javascript">
    var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
    (function(){
    var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
    s1.async=true;
    s1.src='https://embed.tawk.to/64479d7131ebfa0fe7fa4aac/1gurru1lr';
    s1.charset='UTF-8';
    s1.setAttribute('crossorigin','*');
    s0.parentNode.insertBefore(s1,s0);
    })();
    </script>
    <!--End of Tawk.to Script-->
<body>
  <style>
    /* static/css/style.css 

.hero_area {
    background-image: url('{% static "taifa4.PNG" %}');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    height: 100vh; /* Adjust the height as needed 
}*/

/* Add any additional styles for other elements on the page */

  </style>
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="contact_nav_container">
        <div class="container">
          <div class="contact_nav">
            <a href="">
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              <span>
                Address :Nyeri County
              </span>
            </a>
            <a href="">
              <i class="fa fa-envelope" aria-hidden="true"></i>
              <span>
                Email : taifasacco@gmail.com
              </span>
            </a>
            <a href="">
              <i class="fa fa-phone" aria-hidden="true"></i>
              <span>
                Phone Call :0792761073
              </span>
            </a>
          </div>
        </div>
      </div>
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container">
          <div class="custom_menu-btn">
            <button onclick="openNav()">
              <span class="s-1"> </span>
              <span class="s-2"> </span>
              <span class="s-3"> </span>
            </button>
          </div>
          <div id="myNav" class="overlay">
            <div class="menu_btn-style ">
              <button onclick="closeNav()">
                <span class="s-1"> </span>
                <span class="s-2"> </span>
                <span class="s-3"> </span>
              </button>
            </div>
            <div class="overlay-content">
              <a class="active" href="index.html"> Home <span class="sr-only">(current)</span></a>
              <a class="" href="about.html"> About</a>
              <a class="" href="why.html"> Why Us </a>
              <a class="" href="team.html"> Our Team</a>
              <a class="" href="testimonial.html"> Testimonial</a>
              <a class="" href="contact.html"> Contact Us</a>
            </div>
          </div>
          <a class="navbar-brand" href="index.html">
            <span>
              Taifa Sacco 
            </span>
          </a>
          <div class="user_option">
            <a href="{% url 'home' %}">
              <span>
                Home
              </span>
              <i class="fa fa-user" aria-hidden="true"></i>
            </a>
            
          </div>
        </nav>
      </div>
    </header>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
          <form method="post" action="{% url 'authentication:login' %}" class="form-signin">

                {% csrf_token %}
                <h2 class="mb-4">Login</h2>
                {{ form.username }}
                {{ form.password }}
                
                <div class="mb-3"></div>
                <button type="submit" class="btn btn-lg btn-success btn-block">Login</button>
            </form>

            <!-- Link to go back to the register page -->
            <div class="mt-3">
                <a href="{% url 'authentication:register' %}">Don't have an account? Register here</a>
            </div>
        </div>
    </div>
</div>

<section class="info_section layout_padding2">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="info_contact">
            <h5>
              Address
            </h5>
            <div class="contact_link_box">
              <a href="">
                <i class="fa fa-map-marker" aria-hidden="true"></i>
                <span>
                  Location
                </span>
              </a>
              <a href="">
                <i class="fa fa-phone" aria-hidden="true"></i>
                <span>
                  Call 0792761073
                </span>
              </a>
              <a href="">
                <i class="fa fa-envelope" aria-hidden="true"></i>
                <span>
                  taifasacco@gmail.com
                </span>
              </a>
            </div>
          </div>
          <div class="info_social">
            <a href="">
              <i class="fa fa-facebook" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-twitter" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-linkedin" aria-hidden="true"></i>
            </a>
            <a href="">
              <i class="fa fa-instagram" aria-hidden="true"></i>
            </a>
          </div>
        </div>
        <div class="col-md-4">
          <div class="info_link_box">
            <h5>
              Navigation
            </h5>
            <div class="info_links">
              <a class="active" href="index.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Home <span class="sr-only">(current)</span></a>
              <a class="" href="about.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> About</a>
              <a class="" href="why.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Why Us </a>
              <a class="" href="team.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Our Team</a>
              <a class="" href="testimonial.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Testimonial</a>
              <a class="" href="contact.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Contact Us</a>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <h5>
            Newsletter
          </h5>
          <form action="">
            <input type="text" placeholder="Enter Your email" />
            <button type="submit">
              Subscribe
            </button>
          </form>
        </div>
      </div>
    </div>
  </section>

  <!-- end info section -->

  <!-- footer section -->
  <footer class="footer_section container-fluid">
    <p>
      &copy; <span id="displayYear"></span> All Rights Reserved. Developed By
      <a href="https://developer-fullstack.netlify.app/">Bruno</a>
    </p>
  </footer>
  <!-- footer section -->

  
  <script src="{% static 'js/jquery-3.4.1.min.js' %} "></script>
  <script src="{% static 'js/bootstrap.js' %} "></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
  <script src="{% static 'js/custom.js' %} "></script>
  
  

</body>
</html>

templates/response.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Farm Chatbot - Response</title>
</head>
<body>
    <h1>Farm Chatbot - Response</h1>
    <p>{{ response }}</p>
</body>
</html>

templates/update_account.html
{% load  static %}
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />

  <title>Taifa Sacco</title>

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha384-GLhlTQ8iN17Sme8kATtZ8z9HgB2IbrJDOONT7vo1OqU/E15I6ZuPmXzme17FBo" crossorigin="anonymous">

  <!-- bootstrap core css -->
  
  <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
  <!-- fonts awesome style -->
  
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
  <!-- fonts style -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700|Poppins:400,500,700&display=swap" rel="stylesheet" />

  <!-- Custom styles for this template -->
  
  <link href="{% static 'css/style.css' %}" rel="stylesheet">
  <!-- responsive style -->
  
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet">
</head>

<body>
  <style>
    /* static/css/style.css 

.hero_area {
    background-image: url('{% static "taifa4.PNG" %}');
    background-size: cover;
    background-position: center;
    background-repeat: no-repeat;
    height: 100vh; /* Adjust the height as needed 
}*/

/* Add any additional styles for other elements on the page */

  </style>
  <div class="hero_area">
    <!-- header section strats -->
    <header class="header_section">
      <div class="contact_nav_container">
        <div class="container">
          <div class="contact_nav">
            <a href="">
              <i class="fa fa-map-marker" aria-hidden="true"></i>
              <span>
                Address :Nyeri County
              </span>
            </a>
            <a href="">
              <i class="fa fa-envelope" aria-hidden="true"></i>
              <span>
                Email : taifasacco@gmail.com
              </span>
            </a>
            <a href="">
              <i class="fa fa-phone" aria-hidden="true"></i>
              <span>
                Phone Call :0792761073
              </span>
            </a>
          </div>
        </div>
      </div>
      <div class="container-fluid">
        <nav class="navbar navbar-expand-lg custom_nav-container">
          <div class="custom_menu-btn">
            <button onclick="openNav()">
              <span class="s-1"> </span>
              <span class="s-2"> </span>
              <span class="s-3"> </span>
            </button>
          </div>
          <div id="myNav" class="overlay">
            <div class="menu_btn-style ">
              <button onclick="closeNav()">
                <span class="s-1"> </span>
                <span class="s-2"> </span>
                <span class="s-3"> </span>
              </button>
            </div>
            <div class="overlay-content">
              <a class="active" href="index.html"> Home <span class="sr-only">(current)</span></a>
              <a class="" href="about.html"> About</a>
              <a class="" href="why.html"> Why Us </a>
              <a class="" href="team.html"> Our Team</a>
              <a class="" href="testimonial.html"> Testimonial</a>
              <a class="" href="contact.html"> Contact Us</a>
            </div>
          </div>
          <a class="navbar-brand" href="index.html">
            <span>
              Taifa Sacco 
            </span>
          </a>
          <div class="user_option">
            <a href="{% url 'authentication:login' %}">
              <span>
                Login
              </span>
              <i class="fa fa-user" aria-hidden="true"></i>
            </a>
            
          </div>
        </nav>
      </div>
    </header>
    <h5>Update Profile</h5>

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    <form method="post" action="{% url 'authentication:update_account' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit"  style="display: inline-block;
        padding: 10px 15px;
        margin: 5px;
        text-decoration: none;
        color:white;
        background-color: #649713; /* Button color */
        border-radius: 5px;
        transition: background-color 0.3s ease;">Update Account</button>
    </form>

    <section class="info_section layout_padding2">
        <div class="container">
          <div class="row">
            <div class="col-md-4">
              <div class="info_contact">
                <h5>
                  Address
                </h5>
                <div class="contact_link_box">
                  <a href="">
                    <i class="fa fa-map-marker" aria-hidden="true"></i>
                    <span>
                      Location
                    </span>
                  </a>
                  <a href="">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    <span>
                      Call 0792761073
                    </span>
                  </a>
                  <a href="">
                    <i class="fa fa-envelope" aria-hidden="true"></i>
                    <span>
                      taifasacco@gmail.com
                    </span>
                  </a>
                </div>
              </div>
              <div class="info_social">
                <a href="">
                  <i class="fa fa-facebook" aria-hidden="true"></i>
                </a>
                <a href="">
                  <i class="fa fa-twitter" aria-hidden="true"></i>
                </a>
                <a href="">
                  <i class="fa fa-linkedin" aria-hidden="true"></i>
                </a>
                <a href="">
                  <i class="fa fa-instagram" aria-hidden="true"></i>
                </a>
              </div>
            </div>
            <div class="col-md-4">
              <div class="info_link_box">
                <h5>
                  Navigation
                </h5>
                <div class="info_links">
                  <a class="active" href="index.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Home <span class="sr-only">(current)</span></a>
                  <a class="" href="about.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> About</a>
                  <a class="" href="why.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Why Us </a>
                  <a class="" href="team.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Our Team</a>
                  <a class="" href="testimonial.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Testimonial</a>
                  <a class="" href="contact.html"> <i class="fa fa-angle-right" aria-hidden="true"></i> Contact Us</a>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <h5>
                Newsletter
              </h5>
              <form action="">
                <input type="text" placeholder="Enter Your email" />
                <button type="submit">
                  Subscribe
                </button>
              </form>
            </div>
          </div>
        </div>
      </section>
    
      <!-- end info section -->
    
      <!-- footer section -->
      <footer class="footer_section container-fluid">
        <p>
          &copy; <span id="displayYear"></span> All Rights Reserved. Developed By
          <a href="https://developer-fullstack.netlify.app/">Bruno</a>
        </p>
      </footer>
      <!-- footer section -->
    
      
      <script src="{% static 'js/jquery-3.4.1.min.js' %} "></script>
      <script src="{% static 'js/bootstrap.js' %} "></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
      <script src="{% static 'js/custom.js' %} "></script>
      
      
    
</body>
</html>